import test from 'node:test';import assert from 'node:assert/strict';import {PDFDocument} from 'pdf-lib';import {makeProposal} from '../lib/proposal.mjs';import {validate,validTime,sign} from '../lib/security.mjs';import handler from '../api/enquiry.js';import services from '../data/services.json' with {type:'json'};
const input={name:'Test Business',email:'test@example.com',company:'Example',service:'brand-kit',goal:'We need a clearer brand and customer enquiry journey.',budget:'Let’s discuss',timeline:'Exploring options',phone:'',consent:true};
test('all eight service proposals produce readable PDFs',async()=>{for(const s of services){const bytes=await makeProposal({...input,service:s.slug});assert.ok(bytes.length>1000);const doc=await PDFDocument.load(bytes);assert.ok(doc.getPageCount()>=1)}});
test('long and multilingual input stays within generated pages',async()=>{const b=await makeProposal({...input,name:'ನವೀನ್ कुमार',goal:'x'.repeat(2000)});const pdf=await PDFDocument.load(b);assert.ok(pdf.getPageCount()<6)});
test('validation rejects header injection, missing consent and unknown service',()=>{assert.equal(validate(input),null);assert.ok(validate({...input,email:'a@example.com\r\nBcc:x@example.com'}));assert.ok(validate({...input,consent:false}));assert.ok(validate({...input,service:'fake'}));assert.ok(validate({...input,goal:'short'}))});
test('signed timestamps reject tampering, instant and expired requests',()=>{process.env.FORM_SIGNING_SECRET='test-only-secret';let t=Date.now()-5000;assert.ok(validTime(t,sign(t)));assert.equal(validTime(t,'0'.repeat(64)),false);t=Date.now();assert.equal(validTime(t,sign(t)),false);t=Date.now()-8000000;assert.equal(validTime(t,sign(t)),false)});
test('unconfigured endpoint fails closed instead of claiming email delivery',async()=>{delete process.env.RESEND_API_KEY;let status;let payload;const res={setHeader(){},status(n){status=n;return this},json(o){payload=o}};await handler({method:'POST'},res);assert.equal(status,503);assert.ok(payload.error)});
test('verified enquiry sends service PDF and owner copy through provider',async()=>{
 const keys={SITE_URL:'https://agency.example',RESEND_API_KEY:'test',PROPOSAL_FROM_EMAIL:'test@agency.example',TURNSTILE_SITE_KEY:'test',TURNSTILE_SECRET_KEY:'test',UPSTASH_REDIS_REST_URL:'https://redis.example',UPSTASH_REDIS_REST_TOKEN:'test',FORM_SIGNING_SECRET:'test-only-secret'};Object.assign(process.env,keys);const original=globalThis.fetch;let mail;
 globalThis.fetch=async(url,options)=>{if(url==='https://redis.example'){const cmd=JSON.parse(options.body);return new Response(JSON.stringify({result:cmd[0]==='SET'?'OK':1}))}if(String(url).includes('siteverify'))return new Response(JSON.stringify({success:true,hostname:'agency.example',action:'enquiry'}));if(url==='https://api.resend.com/emails'){mail=JSON.parse(options.body);return new Response(JSON.stringify({id:'test-message'}))}throw Error('Unexpected request')};
 try{const issuedAt=Date.now()-5000;let status=200,payload;const res={setHeader(){},status(n){status=n;return this},json(o){payload=o}};await handler({method:'POST',headers:{origin:'https://agency.example','content-type':'application/json'},body:{...input,issuedAt,signature:sign(issuedAt),token:'verified-test-token'}},res);assert.equal(status,200);assert.deepEqual(mail.to,[input.email]);assert.deepEqual(mail.bcc,['make@creatorfox.com']);assert.equal(mail.attachments[0].filename,'CreatorFox-brand-kit-proposal.pdf');assert.ok((await PDFDocument.load(Buffer.from(mail.attachments[0].content,'base64'))).getPageCount());assert.match(payload.message,/accepted for delivery/)}finally{globalThis.fetch=original;for(const k of Object.keys(keys))delete process.env[k]}
});
