import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Bot, BrainCircuit, ChartNoAxesCombined, Zap } from "lucide-react";
import { CreatorDirectory, Footer, MagneticButton, Navbar, Reveal, ServiceGrid, WorkCard } from "../components/SiteUI";
import site from "../content/site.json";

export default function Home(){return <main>
 <Navbar/>
 <section className="relative min-h-screen overflow-hidden bg-[#0A0A0A] pt-36 text-white sm:pt-44"><div className="absolute inset-0 grid-lines opacity-[.22]"/><div className="absolute right-[-12vw] top-[12vh] h-[52vw] w-[52vw] rounded-full border border-[#BB7C1D]/20"/><div className="absolute right-[8vw] top-[22vh] h-[30vw] w-[30vw] rounded-full bg-[#BB7C1D]/10 blur-[90px]"/>
   <div className="relative mx-auto grid min-h-[75vh] max-w-[1440px] items-end gap-10 px-5 pb-14 sm:px-8 sm:pb-20 lg:grid-cols-[1.15fr_.65fr]"><Reveal><p className="eyebrow text-[#BB7C1D]">{site.hero.eyebrow}</p><h1 className="display mt-6 max-w-6xl">Make the market <span className="text-[#BB7C1D]">notice.</span></h1><p className="mt-8 max-w-2xl text-base leading-7 text-white/50 sm:text-lg">{site.hero.description}</p><div className="mt-9 flex flex-wrap gap-3"><MagneticButton href="/contact" label={site.hero.primaryCta} dark/><Link href="/creators" className="group inline-flex items-center gap-3 rounded-full border border-white/15 px-5 py-3 text-[11px] font-bold uppercase tracking-[.14em] text-white/70 hover:border-[#BB7C1D] hover:text-white">{site.hero.secondaryCta}<ArrowDownRight size={15}/></Link></div></Reveal><Reveal delay={.12} className="hidden lg:block"><div className="ml-auto max-w-sm rounded-[28px] border border-white/10 bg-white/[.035] p-6 backdrop-blur-xl"><div className="flex items-center justify-between"><span className="eyebrow text-white/35">Operating system</span><span className="h-2 w-2 rounded-full bg-[#BB7C1D] shadow-[0_0_18px_#BB7C1D]"/></div><div className="mt-12 space-y-5">{['Brand / Positioning','Creative / Content','Performance / Growth','Creators / Distribution','AI / Automation'].map((x,i)=><div key={x} className="flex items-center gap-4 border-b border-white/10 pb-4"><span className="text-xs text-[#BB7C1D]">0{i+1}</span><span className="text-sm text-white/70">{x}</span></div>)}</div></div></Reveal></div>
   <div className="relative mx-auto grid max-w-[1440px] grid-cols-2 border-t border-white/10 sm:grid-cols-4">{site.stats.map(s=><div key={s.label} className="border-r border-white/10 px-5 py-6 sm:px-8"><p className="text-2xl font-bold tracking-[-.04em] sm:text-3xl">{s.value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.13em] text-white/30">{s.label}</p></div>)}</div>
 </section>
 <section className="bg-[#f7f7f5] py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8"><Reveal className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#BB7C1D]">The point of view</p><p className="mt-8 max-w-sm text-sm leading-7 text-black/55">We do not separate brand from growth. We build the system where positioning, creative, media, creators, technology and automation reinforce each other.</p></div><h2 className="text-5xl font-bold leading-[.95] tracking-[-.06em] sm:text-7xl">Less noise.<br/>More <span className="text-[#BB7C1D]">signal.</span></h2></Reveal><div className="mt-20 grid gap-6 border-t border-black/10 pt-6 md:grid-cols-3">{[['01','Clarity','Know exactly who you are, who you serve and why you win.'],['02','Velocity','Ship ideas quickly without turning quality into a casualty.'],['03','Leverage','Use creators, paid media, code and AI as force multipliers.']].map(([n,t,c],i)=><Reveal delay={i*.06} key={n}><span className="text-xs font-bold text-[#BB7C1D]">{n}</span><h3 className="mt-10 text-2xl font-bold">{t}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-black/50">{c}</p></Reveal>)}</div></div></section>
 <section className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8"><Reveal className="mb-12 flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="eyebrow text-[#BB7C1D]">What we build</p><h2 className="mt-4 text-5xl font-bold tracking-[-.055em] sm:text-7xl">Seven unfair<br/>advantages.</h2></div><p className="max-w-md text-sm leading-7 text-black/50">A deliberately tight service stack. Enough range to solve the growth problem; enough focus to stay accountable to the outcome.</p></Reveal><ServiceGrid/></div></section>
 <section className="bg-[#f0f0ed] py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8"><Reveal className="grid gap-10 lg:grid-cols-[1fr_.65fr]"><div><p className="eyebrow text-[#BB7C1D]">CreatorFox Marketplace</p><h2 className="mt-5 text-5xl font-bold tracking-[-.06em] sm:text-8xl">People<br/>with <span className="text-[#BB7C1D]">pull.</span></h2></div><div className="self-end"><p className="text-sm leading-7 text-black/55">A curated Indian creator network for campaigns that need relevance, not vanity metrics. Filter by niche and city, inspect performance and shortlist creators in minutes.</p><Link href="/creators" className="mt-7 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.14em]">Open marketplace <ArrowUpRight size={15}/></Link></div></Reveal><div className="mt-14"><CreatorDirectory/></div></div></section>
 <section className="bg-[#0A0A0A] py-24 text-white sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8"><Reveal className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-[#BB7C1D]">AI / Automation</p><h2 className="mt-6 text-5xl font-bold leading-[.95] tracking-[-.06em] sm:text-7xl">Turn busywork<br/>into <span className="text-[#BB7C1D]">infrastructure.</span></h2><p className="mt-7 max-w-sm text-sm leading-7 text-white/45">Practical agents and workflows for marketing, sales, support, reporting and internal operations.</p></div><div className="grid gap-px bg-white/10 sm:grid-cols-3">{[[Bot,'Agents','Research, qualify, summarize and route work.'],[Zap,'Workflows','Connect CRM, forms, inboxes and analytics.'],[BrainCircuit,'Workshops','Give teams a practical AI operating playbook.']].map(([Icon,t,c])=>{const I=Icon as any;return <div key={t as string} className="bg-[#0A0A0A] p-7 transition hover:bg-[#121212]"><I className="text-[#BB7C1D]" size={22} strokeWidth={1.4}/><h3 className="mt-14 text-xl font-bold">{t as string}</h3><p className="mt-3 text-sm leading-6 text-white/45">{c as string}</p><ArrowUpRight className="mt-8 text-white/20" size={18}/></div>})}</div></Reveal></div></section>
 <section className="bg-[#f7f7f5] py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8"><Reveal><p className="eyebrow text-[#BB7C1D]">Selected work</p><h2 className="mt-5 max-w-4xl text-5xl font-bold tracking-[-.06em] sm:text-7xl">Work that moves<br/><span className="text-[#BB7C1D]">numbers.</span></h2></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{site.work.map((w,i)=><Reveal key={w.title} delay={i*.07}><WorkCard work={w}/></Reveal>)}</div><div className="mt-10"><Link href="/work" className="inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.14em]">View all work <ArrowUpRight size={15}/></Link></div></div></section>
 <section className="bg-[#BB7C1D] py-24 text-white sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8"><Reveal><p className="eyebrow text-white/60">Ready when you are</p><h2 className="mt-5 max-w-5xl text-5xl font-bold leading-[.92] tracking-[-.06em] sm:text-8xl">Your next growth<br/>move starts here.</h2><p className="mt-8 max-w-xl text-sm leading-7 text-white/75">Tell us what is stuck, what needs to grow and where you want to go. We will map the opportunity before we recommend the work.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-3 rounded-full bg-white px-6 py-4 text-[11px] font-bold uppercase tracking-[.14em] text-[#2B2B2B]">Start a project <ArrowUpRight size={15}/></Link></Reveal></div></section>
 <footer><div className="bg-[#0A0A0A] px-5 py-12 text-white"><div className="mx-auto max-w-[1440px] flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-[#BB7C1D]">CreatorFox</p><p className="mt-3 text-sm text-white/40">Strategy · Creative · Performance · AI</p></div><Link href="/contact" className="text-sm font-bold">hello@creatorfox.com ↗</Link></div></div></footer>
 </main>}
