import Link from "next/link";
import {ArrowDownRight,ArrowUpRight,ArrowRight,Play} from "lucide-react";
import {CreatorDirectory,Footer,MagneticButton,Navbar,Reveal,WorkCard} from "../components/SiteUI";
import ServicesShowcase from "../components/ServicesShowcase";
import FallingText from "../components/FallingText";
import EvilEye from "../components/EvilEye";
import ScrollExpand from "../components/ScrollExpand";
import site from "../content/site.json";

const abstract="https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=2200&q=90";
export default function Home(){return <main>
<Navbar/>
<section className="relative min-h-screen overflow-hidden bg-[#070707] pt-32 text-white sm:pt-40 scanline"><div className="absolute inset-0 grid-lines"/><div className="absolute -right-40 top-20 h-[70vw] w-[70vw] rounded-full border border-[#BB7C1D]/15"/><div className="absolute right-[8vw] top-[12vh] h-[42vw] w-[42vw] rounded-full bg-[#BB7C1D]/10 blur-[130px]"/><div className="relative mx-auto grid min-h-[78vh] max-w-[1500px] items-center gap-12 px-5 pb-16 sm:px-8 lg:grid-cols-[1.1fr_.9fr]"><Reveal><p className="eyebrow text-[#BB7C1D]">{site.hero.eyebrow}</p><h1 className="display mt-7 max-w-6xl">Make the market <span className="text-[#BB7C1D]">notice.</span></h1><p className="mt-8 max-w-2xl text-base leading-7 text-white/50 sm:text-lg">A cinematic growth partner combining brand, digital, performance, creators and AI into one system built to create attention and revenue.</p><div className="mt-9 flex flex-wrap gap-3"><MagneticButton href="/contact" label="Start a project" dark/><Link href="/case-studies" className="group inline-flex items-center gap-3 rounded-full border border-white/15 px-5 py-3 text-[11px] font-bold uppercase tracking-[.14em] text-white/70 hover:border-[#BB7C1D] hover:text-white">See case studies <ArrowDownRight size={15}/></Link></div></Reveal><Reveal delay={.12} className="relative hidden lg:block"><div className="relative ml-auto aspect-[4/5] max-w-[520px] overflow-hidden rounded-[40px] border border-white/10 bg-[#111]"><img src={abstract} alt="Abstract creative direction for CreatorFox" className="h-full w-full object-cover opacity-55 mix-blend-screen"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_40%,rgba(187,124,29,.35),transparent_42%),linear-gradient(135deg,rgba(0,0,0,.9),transparent,rgba(187,124,29,.12))]"/><div className="absolute inset-8 rounded-[30px] border border-[#BB7C1D]/25"/><div className="absolute inset-x-7 bottom-7"><p className="eyebrow text-[#BB7C1D]">CreatorFox / 2026</p><p className="mt-3 text-3xl font-bold leading-none tracking-[-.05em]">Brand × Digital<br/>× Creators × AI</p></div><div className="absolute right-7 top-7 h-24 w-24 rounded-full border border-[#BB7C1D]/30 p-2 float"><EvilEye/></div></div></Reveal></div><div className="relative mx-auto grid max-w-[1500px] grid-cols-2 border-t border-white/10 sm:grid-cols-4">{site.stats.map(s=><div key={s.label} className="border-r border-white/10 px-5 py-6 sm:px-8"><p className="text-2xl font-bold sm:text-3xl">{s.value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.13em] text-white/30">{s.label}</p></div>)}</div></section>
<section className="relative overflow-hidden bg-[#f7f7f5] py-24 sm:py-32"><div className="mx-auto max-w-[1500px] px-5 sm:px-8"><Reveal className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow text-[#BB7C1D]">The Fox Principle</p><p className="mt-8 max-w-sm text-sm leading-7 text-black/55">Move quietly. See the pattern early. Strike with precision. CreatorFox is built around the same instinct: clarity before noise, systems before scale.</p></div><div><FallingText text="Strategy Creative Technology Performance Creators Intelligence" highlightWords={["Creative","Performance","Creators","Intelligence"]} fontSize="clamp(2rem,4.5vw,4.8rem)"/></div></Reveal></div></section>
<ScrollExpand src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=2400&q=90" alt="Abstract digital growth environment" title="Build what people remember."><div><p className="eyebrow text-[#BB7C1D]">Scroll into the system</p><h3 className="mt-4 text-4xl font-bold sm:text-7xl">One fox.<br/>Many moves.</h3><Link href="/services" className="mt-8 inline-flex rounded-full bg-[#BB7C1D] px-6 py-4 text-xs font-bold uppercase tracking-widest">Explore services <ArrowRight size={15}/></Link></div></ScrollExpand>
<ServicesShowcase/>
<section className="bg-[#f0f0ed] py-24 sm:py-32"><div className="mx-auto max-w-[1500px] px-5 sm:px-8"><Reveal className="grid gap-10 lg:grid-cols-[1fr_.6fr]"><div><p className="eyebrow text-[#BB7C1D]">Indian Creator Network</p><h2 className="mt-5 text-5xl font-bold tracking-[-.06em] sm:text-8xl">People<br/>with <span className="text-[#BB7C1D]">pull.</span></h2></div><div className="self-end"><p className="text-sm leading-7 text-black/55">A curated influencer marketplace for brand campaigns that need relevance, audience quality and creative fit — not vanity metrics.</p><Link href="/creators" className="mt-7 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.14em]">Open influencer list <ArrowUpRight size={15}/></Link></div></Reveal><div className="mt-14"><CreatorDirectory/></div></div></section>
<section className="bg-[#080808] py-24 text-white sm:py-32"><div className="mx-auto max-w-[1500px] px-5 sm:px-8"><Reveal><p className="eyebrow text-[#BB7C1D]">AI workshops & automation</p><h2 className="mt-6 max-w-5xl text-5xl font-bold leading-[.92] tracking-[-.06em] sm:text-8xl">Make AI your<br/><span className="text-[#BB7C1D]">unfair advantage.</span></h2></Reveal><div className="mt-16 grid gap-px bg-white/10 md:grid-cols-3"><Link href="/ai-workshop" className="tilt-card bg-[#080808] p-8"><p className="eyebrow text-[#BB7C1D]">01 / Workshop</p><h3 className="mt-20 text-2xl font-bold">Executive AI Workshops</h3><p className="mt-3 text-sm leading-6 text-white/45">Hands-on AI training for founders, leaders and marketing teams.</p><ArrowUpRight className="mt-8 text-[#BB7C1D]" size={20}/></Link><Link href="/ai-automation" className="tilt-card bg-[#080808] p-8"><p className="eyebrow text-[#BB7C1D]">02 / Build</p><h3 className="mt-20 text-2xl font-bold">AI Agents & Automation</h3><p className="mt-3 text-sm leading-6 text-white/45">Connect CRM, forms, WhatsApp, email and analytics into intelligent workflows.</p><ArrowUpRight className="mt-8 text-[#BB7C1D]" size={20}/></Link><div className="relative overflow-hidden bg-[#080808] p-8"><div className="absolute -right-20 -top-20 h-72 w-72 opacity-90"><EvilEye/></div><p className="relative eyebrow text-[#BB7C1D]">03 / Intelligence</p><h3 className="relative mt-20 text-2xl font-bold">See the signal.</h3><p className="relative mt-3 max-w-xs text-sm leading-6 text-white/45">Dashboards, reporting and AI-assisted decision systems that turn activity into direction.</p></div></div></div></section>
<section className="bg-[#f7f7f5] py-24 sm:py-32"><div className="mx-auto max-w-[1500px] px-5 sm:px-8"><Reveal><p className="eyebrow text-[#BB7C1D]">Selected case studies</p><h2 className="mt-5 max-w-4xl text-5xl font-bold tracking-[-.06em] sm:text-7xl">Work that moves<br/><span className="text-[#BB7C1D]">numbers.</span></h2></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{site.work.map((w,i)=><Reveal key={w.title} delay={i*.07}><WorkCard work={w}/></Reveal>)}</div><Link href="/case-studies" className="mt-10 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.14em]">View all case studies <ArrowUpRight size={15}/></Link></div></section>
<section className="relative overflow-hidden bg-[#BB7C1D] py-24 text-white sm:py-32"><div className="absolute -right-20 -top-20 h-96 w-96 opacity-40"><EvilEye/></div><div className="relative mx-auto max-w-[1500px] px-5 sm:px-8"><Reveal><p className="eyebrow text-white/60">Ready when you are</p><h2 className="mt-5 max-w-5xl text-5xl font-bold leading-[.92] tracking-[-.06em] sm:text-8xl">Your next growth<br/>move starts here.</h2><Link href="/contact" className="mt-9 inline-flex items-center gap-3 rounded-full bg-white px-6 py-4 text-[11px] font-bold uppercase tracking-[.14em] text-[#2B2B2B]">Start a project <ArrowUpRight size={15}/></Link></Reveal></div></section><Footer/></main>}
