"use client";
import {useEffect,useRef,useState} from "react";
import Matter from "matter-js";
import "./FallingText.css";

type Props={text:string;highlightWords?:string[];highlightClass?:string;trigger?:"click"|"hover"|"auto"|"scroll";backgroundColor?:string;wireframes?:boolean;gravity?:number;mouseConstraintStiffness?:number;fontSize?:string;wordSpacing?:string;className?:string};
export default function FallingText({text,highlightWords=[],highlightClass="highlighted",trigger="scroll",backgroundColor="transparent",wireframes=false,gravity=.56,mouseConstraintStiffness=.9,fontSize="2rem",wordSpacing="4px",className=""}:Props){
 const root=useRef<HTMLDivElement>(null), target=useRef<HTMLDivElement>(null), canvas=useRef<HTMLDivElement>(null); const [started,setStarted]=useState(trigger==="auto");
 useEffect(()=>{if(!target.current)return;target.current.innerHTML=text.split(" ").map(w=>`<span class="word ${highlightWords.some(h=>w.startsWith(h))?highlightClass:""}">${w}</span>`).join(" ")},[text,highlightWords,highlightClass]);
 useEffect(()=>{if(trigger==="scroll"&&root.current){const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){setStarted(true);o.disconnect()}},{threshold:.2});o.observe(root.current);return()=>o.disconnect()}},[trigger]);
 useEffect(()=>{if(!started||!root.current||!target.current||!canvas.current)return;const r=root.current,rect=r.getBoundingClientRect(),w=rect.width,h=rect.height;if(!w||!h)return;const E=Matter.Engine.create();E.world.gravity.y=gravity;const R=Matter.Render.create({element:canvas.current,engine:E,options:{width:w,height:h,background:backgroundColor,wireframes,pixelRatio:Math.min(window.devicePixelRatio||1,2)}});const wall={isStatic:true,render:{fillStyle:"transparent"}};const bounds=[Matter.Bodies.rectangle(w/2,h+25,w,50,wall),Matter.Bodies.rectangle(-25,h/2,50,h,wall),Matter.Bodies.rectangle(w+25,h/2,50,h,wall)];const bodies=[...target.current.querySelectorAll<HTMLElement>(".word")].map(el=>{const b=el.getBoundingClientRect(),body=Matter.Bodies.rectangle(b.left-rect.left+b.width/2,b.top-rect.top+b.height/2,b.width,b.height,{render:{fillStyle:"transparent"},restitution:.72,friction:.2,frictionAir:.012});Matter.Body.setVelocity(body,{x:(Math.random()-.5)*3,y:0});Matter.Body.setAngularVelocity(body,(Math.random()-.5)*.035);return{el,body}});bodies.forEach(({el})=>{el.style.position="absolute";el.style.pointerEvents="none"});const mouse=Matter.Mouse.create(r),mc=Matter.MouseConstraint.create(E,{mouse,constraint:{stiffness:mouseConstraintStiffness,render:{visible:false}}});R.mouse=mouse;Matter.World.add(E.world,[...bounds,mc,...bodies.map(x=>x.body)]);const runner=Matter.Runner.create();Matter.Runner.run(runner,E);Matter.Render.run(R);let raf=0;const loop=()=>{bodies.forEach(({el,body})=>{el.style.left=`${body.position.x}px`;el.style.top=`${body.position.y}px`;el.style.transform=`translate(-50%,-50%) rotate(${body.angle}rad)`});Matter.Engine.update(E);raf=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(raf);Matter.Render.stop(R);Matter.Runner.stop(runner);R.canvas.remove();Matter.World.clear(E.world,false);Matter.Engine.clear(E)}},[started,gravity,wireframes,backgroundColor,mouseConstraintStiffness]);
 return <div ref={root} className={`falling-text-container ${className}`} onMouseEnter={()=>trigger==="hover"&&setStarted(true)} onClick={()=>trigger==="click"&&setStarted(true)}><div ref={target} className="falling-text-target" style={{fontSize,lineHeight:1.3}}/><div ref={canvas} className="falling-text-canvas"/><style jsx>{`.word{margin:0 ${wordSpacing};}.highlighted{color:#BB7C1D;font-weight:800;}`}</style></div>
}
