"use client";

import { useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, BadgeCheck, BarChart3, BrainCircuit, Bot, BriefcaseBusiness, ChartNoAxesCombined, ChevronDown, CircleArrowUpRight, Globe2, Instagram, Mail, Menu, PenTool, Play, Sparkles, Users, X, Zap } from "lucide-react";
import Logo from "./Logo";

export const services = [
  {slug:"brand-identity",title:"Brand Identity",short:"Positioning, identity systems and launch-ready brand assets.",icon:Sparkles,body:"Build a brand system people recognize before they read the name. We combine positioning, visual direction, messaging and usable brand assets so every touchpoint feels deliberate."},
  {slug:"website-development",title:"Website Development",short:"Premium websites engineered for speed, trust and conversion.",icon:Globe2,body:"Strategy-led websites with premium interaction design, conversion architecture, SEO foundations, analytics and a clean content structure your team can actually manage."},
  {slug:"content-strategy",title:"Content Strategy",short:"A repeatable content engine built around audience, offers and outcomes.",icon:PenTool,body:"Turn scattered posting into an editorial system: content pillars, formats, production workflows, hooks, distribution and reporting designed around business outcomes."},
  {slug:"performance-marketing",title:"Performance Marketing",short:"Google, Meta and LinkedIn campaigns built around profitable growth.",icon:ChartNoAxesCombined,body:"Paid acquisition built around economics. We structure campaigns, landing pages, creative testing, tracking and optimization around qualified leads, sales and ROAS."},
  {slug:"creator-marketing",title:"Creator Marketing",short:"Indian creator discovery, campaign strategy, negotiation and execution.",icon:Users,body:"Find the right Indian voices for the brief, not simply the biggest follower count. CreatorFox handles discovery, shortlisting, outreach, negotiation, briefing and reporting."},
  {slug:"ai-automation",title:"AI & Automation",short:"Agents and workflows that remove repetitive work and accelerate response.",icon:Bot,body:"Connect forms, CRM, WhatsApp, email, documents and internal tools with AI agents and practical workflows that reduce manual work without losing human control."},
  {slug:"ai-workshops",title:"Executive AI Workshops",short:"Practical AI training for founders, marketing teams and leadership.",icon:BrainCircuit,body:"Hands-on sessions that turn AI from a buzzword into an operating skill: research, content, sales enablement, automation opportunities and responsible adoption."}
];

export const creators = [
  {slug:"riya-mehta",name:"Riya Mehta",handle:"@riyamehta.style",city:"Mumbai",niche:"Fashion",followers:"184K",engagement:"4.8%",rate:"₹35K+",image:"https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85",verified:true},
  {slug:"aarav-kapoor",name:"Aarav Kapoor",handle:"@aaravbuilds",city:"Bengaluru",niche:"Tech",followers:"92K",engagement:"6.2%",rate:"₹28K+",image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85",verified:true},
  {slug:"simran-kaur",name:"Simran Kaur",handle:"@simranmoves",city:"Delhi",niche:"Fitness",followers:"276K",engagement:"5.1%",rate:"₹45K+",image:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85",verified:true},
  {slug:"kabir-shah",name:"Kabir Shah",handle:"@kabir.eats",city:"Pune",niche:"Food",followers:"121K",engagement:"7.4%",rate:"₹24K+",image:"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=85",verified:true},
  {slug:"anaya-iyer",name:"Anaya Iyer",handle:"@anaya.skin",city:"Chennai",niche:"Beauty",followers:"318K",engagement:"3.9%",rate:"₹55K+",image:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=85",verified:true},
  {slug:"dev-malhotra",name:"Dev Malhotra",handle:"@devtravels",city:"Hyderabad",niche:"Lifestyle",followers:"68K",engagement:"8.1%",rate:"₹18K+",image:"https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=900&q=85",verified:true}
];

const nav=[['Services','/services'],['Work','/work'],['Creators','/creators'],['AI & Automation','/ai-automation'],['About','/about']];

export function Navbar(){
 const [open,setOpen]=useState(false);
 return <header className="fixed inset-x-0 top-0 z-50 px-3 pt-3 sm:px-6">
   <div className="mx-auto flex max-w-[1440px] items-center justify-between rounded-2xl border border-black/10 bg-[#f7f7f5]/90 px-4 py-3 shadow-[0_18px_50px_rgba(0,0,0,.08)] backdrop-blur-xl sm:px-6">
    <Link href="/" onClick={()=>setOpen(false)}><Logo/></Link>
    <nav className="hidden items-center gap-7 lg:flex">{nav.map(([label,href])=><Link key={href} href={href} className="text-[12px] font-semibold uppercase tracking-[.12em] text-[#2b2b2b]/65 transition hover:text-[#BB7C1D]">{label}</Link>)}</nav>
    <div className="flex items-center gap-2"><Link href="/contact" className="hidden rounded-full bg-[#2B2B2B] px-5 py-3 text-[11px] font-bold uppercase tracking-[.14em] text-white transition hover:bg-[#BB7C1D] sm:inline-flex">Start a project</Link><button aria-label="Open menu" onClick={()=>setOpen(!open)} className="grid h-11 w-11 place-items-center rounded-full border border-black/10 lg:hidden">{open?<X size={19}/>:<Menu size={19}/>}</button></div>
   </div>
   <AnimatePresence>{open&&<motion.div initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} className="mx-auto mt-2 max-w-[1440px] rounded-2xl border border-black/10 bg-[#f7f7f5] p-5 shadow-xl lg:hidden">{nav.map(([label,href])=><Link onClick={()=>setOpen(false)} key={href} href={href} className="block border-b border-black/5 py-4 text-lg font-semibold">{label}</Link>)}<Link onClick={()=>setOpen(false)} href="/contact" className="mt-4 flex items-center justify-between rounded-xl bg-[#BB7C1D] px-4 py-4 font-bold text-white">Start a project <ArrowUpRight size={18}/></Link></motion.div>}</AnimatePresence>
 </header>
}

export function Reveal({children,className="",delay=0}:{children:React.ReactNode;className?:string;delay?:number}){return <motion.div className={className} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.7,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}

export function PageHero({eyebrow,title,description,dark=false}:{eyebrow:string;title:string;description:string;dark?:boolean}){return <section className={`${dark?'bg-[#0A0A0A] text-white':'bg-[#f7f7f5] text-[#2B2B2B]'} relative overflow-hidden pt-40 pb-20 sm:pb-28`}><div className="absolute right-[-12vw] top-24 h-[42vw] w-[42vw] rounded-full border border-[#BB7C1D]/20"/><div className="absolute right-[4vw] top-36 h-[24vw] w-[24vw] rounded-full bg-[#BB7C1D]/10 blur-3xl"/><div className="mx-auto max-w-[1440px] px-5 sm:px-8"><Reveal><p className="eyebrow text-[#BB7C1D]">{eyebrow}</p><h1 className="display mt-6 max-w-5xl">{title}</h1><p className={`mt-8 max-w-2xl text-base leading-7 ${dark?'text-white/55':'text-[#2B2B2B]/60'}`}>{description}</p></Reveal></div></section>}

export function MagneticButton({href,label,dark=false}:{href:string;label:string;dark?:boolean}){return <Link href={href} className={`group inline-flex items-center gap-3 rounded-full px-5 py-3 text-[11px] font-bold uppercase tracking-[.14em] transition ${dark?'bg-white text-[#2B2B2B] hover:bg-[#BB7C1D] hover:text-white':'bg-[#2B2B2B] text-white hover:bg-[#BB7C1D]'}`}>{label}<span className="grid h-6 w-6 place-items-center rounded-full bg-white/10 transition group-hover:rotate-45"><ArrowUpRight size={13}/></span></Link>}

export function ServiceGrid(){return <div className="grid border-l border-t border-black/10 sm:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=>{const Icon=s.icon;return <Link href={`/services/${s.slug}`} key={s.slug} className="group border-b border-r border-black/10 p-7 transition duration-500 hover:bg-[#2B2B2B] hover:text-white sm:p-9"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full border border-black/10 text-[#BB7C1D] transition group-hover:border-white/20"><Icon size={20} strokeWidth={1.5}/></span><span className="text-[10px] font-bold text-black/30 group-hover:text-white/35">0{i+1}</span></div><h3 className="mt-16 text-2xl font-bold tracking-[-.03em]">{s.title}</h3><p className="mt-3 text-sm leading-6 text-black/50 group-hover:text-white/55">{s.short}</p><ArrowUpRight className="mt-8 text-black/30 transition group-hover:translate-x-1 group-hover:-translate-y-1 group-hover:text-[#BB7C1D]" size={20}/></Link>})}</div>}

export function CreatorCard({creator}:{creator:any}){return <Link href={`/creators/${creator.slug}`} className="group block overflow-hidden rounded-[22px] bg-white"><div className="relative aspect-[4/5] overflow-hidden bg-[#ddd]"><img src={creator.image} alt={creator.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-x-3 top-3 flex items-center justify-between"><span className="rounded-full bg-white/90 px-3 py-2 text-[10px] font-bold uppercase tracking-[.12em]">{creator.niche}</span>{creator.verified&&<span className="grid h-8 w-8 place-items-center rounded-full bg-white/90 text-[#BB7C1D]"><BadgeCheck size={17}/></span>}</div><div className="absolute inset-x-3 bottom-3 flex items-end justify-between rounded-2xl bg-black/55 p-3 text-white backdrop-blur-md"><div><p className="text-sm font-bold">{creator.name}</p><p className="text-[11px] text-white/60">{creator.city}, India</p></div><Instagram size={16}/></div></div><div className="grid grid-cols-3 divide-x divide-black/10 p-4"><div><p className="text-[10px] uppercase tracking-widest text-black/40">Followers</p><p className="mt-1 font-bold">{creator.followers}</p></div><div className="pl-3"><p className="text-[10px] uppercase tracking-widest text-black/40">ER</p><p className="mt-1 font-bold">{creator.engagement}</p></div><div className="pl-3"><p className="text-[10px] uppercase tracking-widest text-black/40">From</p><p className="mt-1 font-bold">{creator.rate}</p></div></div></Link>}

export function CreatorDirectory(){const [niche,setNiche]=useState('All');const [city,setCity]=useState('All');const niches=['All','Fashion','Tech','Fitness','Food','Beauty','Lifestyle'];const cities=['All','Mumbai','Bengaluru','Delhi','Pune','Chennai','Hyderabad'];const filtered=creators.filter(c=>(niche==='All'||c.niche===niche)&&(city==='All'||c.city===city));return <div><div className="mb-8 flex flex-wrap gap-2">{niches.map(n=><button key={n} onClick={()=>setNiche(n)} className={`rounded-full border px-4 py-2 text-[10px] font-bold uppercase tracking-[.12em] ${niche===n?'border-[#2B2B2B] bg-[#2B2B2B] text-white':'border-black/10 bg-white text-black/55'}`}>{n}</button>)}<select value={city} onChange={e=>setCity(e.target.value)} className="rounded-full border border-black/10 bg-white px-4 py-2 text-[10px] font-bold uppercase tracking-[.12em] outline-none"><option value="All">All cities</option>{cities.slice(1).map(c=><option key={c}>{c}</option>)}</select></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(c=><CreatorCard key={c.slug} creator={c}/>)}</div></div>}

export function WorkCard({work}:{work:any}){return <article className="group overflow-hidden rounded-[28px] bg-white"><div className="relative aspect-[16/10] overflow-hidden"><img src={work.image} alt={work.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between text-white"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#BB7C1D]">{work.category}</p><h3 className="mt-2 text-2xl font-bold">{work.title}</h3></div><ArrowUpRight size={21}/></div></div><div className="grid grid-cols-2 p-5"><div><p className="text-3xl font-bold">{work.metric}</p><p className="mt-1 text-xs text-black/45">{work.label}</p></div><span className="justify-self-end self-center rounded-full border border-black/10 px-3 py-2 text-[10px] font-bold uppercase tracking-widest">Case study</span></div></article>}

export function Footer(){return <footer className="bg-[#0A0A0A] text-white"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8"><div className="grid gap-12 lg:grid-cols-[1.2fr_.8fr_.8fr]"><div><Logo dark/><h2 className="mt-10 max-w-2xl text-4xl font-bold leading-[1.02] tracking-[-.05em] sm:text-6xl">Build a brand people remember.</h2><Link href="/contact" className="mt-8 inline-flex items-center gap-3 rounded-full bg-[#BB7C1D] px-5 py-3 text-[11px] font-bold uppercase tracking-[.14em]">Start a project <ArrowUpRight size={15}/></Link></div><div><p className="eyebrow text-[#BB7C1D]">Explore</p>{nav.map(([label,href])=><Link key={href} href={href} className="mt-4 block text-sm text-white/55 hover:text-white">{label}</Link>)}</div><div><p className="eyebrow text-[#BB7C1D]">Contact</p><a href="mailto:hello@creatorfox.com" className="mt-4 block text-sm text-white/55 hover:text-white">hello@creatorfox.com</a><p className="mt-2 text-sm text-white/55">India · Global delivery</p><Link href="/admin" className="mt-10 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-white/30 hover:text-white"><BriefcaseBusiness size={13}/> Admin dashboard</Link></div></div><div className="mt-16 flex flex-col justify-between gap-3 border-t border-white/10 pt-6 text-[10px] font-bold uppercase tracking-[.15em] text-white/25 sm:flex-row"><span>© {new Date().getFullYear()} CreatorFox</span><span>Strategy · Creative · Performance · AI</span></div></div></footer>}

export function Process(){const steps=[['01','Diagnose','Audience, offer, competitors, data and current bottlenecks.'],['02','Design','Positioning, creative direction, journeys and conversion architecture.'],['03','Build','Web, content, paid media, creator programs and automation.'],['04','Scale','Measure what matters, improve what works and compound the gains.']];return <div className="grid border-l border-t border-black/10 md:grid-cols-4">{steps.map(([n,t,c])=><div key={n} className="border-b border-r border-black/10 p-7 sm:p-8"><span className="text-xs font-bold text-[#BB7C1D]">{n}</span><h3 className="mt-14 text-2xl font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-black/50">{c}</p></div>)}</div>}

export function ContactForm(){const [sent,setSent]=useState(false);return <form onSubmit={e=>{e.preventDefault();setSent(true)}} className="grid gap-4">{sent?<div className="rounded-2xl bg-[#2B2B2B] p-8 text-white"><p className="eyebrow text-[#BB7C1D]">Message received</p><h3 className="mt-3 text-3xl font-bold">We&apos;ll get back to you.</h3><p className="mt-3 text-sm text-white/55">This demo form is ready to connect to your CRM or email workflow.</p></div>:<><div className="grid gap-4 sm:grid-cols-2"><input required placeholder="Your name" className="field"/><input required type="email" placeholder="Work email" className="field"/></div><input placeholder="Company / website" className="field"/><select className="field"><option>What do you need?</option>{services.map(s=><option key={s.slug}>{s.title}</option>)}</select><textarea required placeholder="Tell us about the project, target and timeline" rows={6} className="field resize-none"/><button className="inline-flex w-fit items-center gap-3 rounded-full bg-[#BB7C1D] px-6 py-4 text-[11px] font-bold uppercase tracking-[.14em] text-white">Send enquiry <ArrowUpRight size={15}/></button></>}</form>}
