import services from '../data/services.json' with {type:'json'};
const detail={
'brand-kit': ['We examine who you serve, what customers value and how your competitors present themselves. You leave with an agreed positioning direction and a useful creative brief.','We develop a coherent identity system: logo variations, colour pairings, typography and clear rules for using them across digital and print.','Your brand guide explains the everyday decisions: how to introduce your business, write a headline, choose imagery and keep communication recognisable.','Launch with editable social and sales templates. Your team can produce consistent material without rebuilding the brand for every new post or pitch.'],
'3d-website-development':['We map the customer journey and identify the pages, product explanations and calls to action needed to turn interest into a meaningful next step.','Design and development work together. Layouts adapt to phones, tablets and desktops, with clear typography, accessible controls and reusable page components.','Interactive product views, depth and motion are added where they help people understand your offer. Mobile fallbacks preserve the story on less powerful devices.','We review metadata, indexability, forms, keyboard access and performance before launch. Handover includes practical guidance for maintaining the site.'],
'content-marketing':['We turn customer questions, buying objections and your expertise into a focused set of topics. Every topic has an audience, a purpose and a place in the journey.','Choose the formats that fit the message: articles that answer questions, short videos that demonstrate value and social posts that start a useful conversation.','AI assists with exploration and production. A human editor checks accuracy, tone, clarity and relevance, with your approval before publication.','A shared calendar makes the programme visible. Reviews connect content activity to meaningful engagement, enquiries and the questions your sales team hears.'],
'performance-marketing':['We choose channels around how your customers discover and buy, then agree the offer, budget, geography and quality criteria for an enquiry.','We review measurement before scaling spend. Conversion events, landing pages and lead handling need to tell a consistent story about campaign performance.','Campaigns become a disciplined sequence of tests: different creative, offers, audiences and landing-page messages, with decisions grounded in the available data.','Reporting explains what was spent, what happened and what changes next. Lead quality and business outcomes matter alongside clicks and impressions.'],
'influencer-marketing':['We shortlist creators around category, location, audience relevance and content quality. A large following alone is not a reason to select someone.','Available audience insights and engagement patterns inform due diligence. We document limitations rather than present follower-authenticity estimates as certainty.','A clear brief sets expectations for the story, format, dates, approvals and disclosure. Coordination keeps both the brand and creator aligned.','Usage rights and distribution are agreed before content goes live. The campaign review separates reach, engagement, traffic and attributable enquiries.'],
'aeo-geo':['We establish a baseline using agreed search terms and customer questions. This makes later visibility reviews more useful than isolated screenshots.','We organise expertise into clear topic areas and publish direct, evidence-led answers. Content is written for people making a decision, not just ranking systems.','Technical checks help search systems access and interpret your pages. Structured data is used only where it accurately represents the content.','We monitor a consistent set of queries, look for citation opportunities and refresh weak content. AI answer placement is variable and never guaranteed.'],
'ai-workshop':['Before the session, we identify the tasks taking up your team’s time, their confidence with AI and any restrictions on tools or business information.','Exercises use realistic business scenarios. Participants practise prompting, reviewing outputs and spotting where a human decision is still required.','The team leaves with reusable prompts, examples and workflow notes. The aim is something they can repeat confidently after the workshop ends.','We discuss safe information handling, verification and ownership. A short action plan identifies a few workflows to trial and how to review their value.'],
'digital-ai-consulting':['We map the journey from customer interest to delivery and identify where manual work, duplicated tools or unclear responsibilities create friction.','Each opportunity is assessed for usefulness, effort and risk. We consider whether a process should be simplified before adding another tool or automation.','The roadmap turns findings into an achievable sequence of work. Each priority has a purpose, owner, dependencies and a way to assess progress.','You can implement with your team or scope delivery with CreatorFox. Reviews focus on adoption and results, not simply whether a tool was installed.']};
const section=(k,h,c)=>`<section class="section"><div class="wrap"><span class="eyebrow">${k}</span><h2>${h}</h2>${c}</div></section>`;
const matrix=(s)=>`<div class="scope-explorer" data-explorer><div class="scope-tabs" role="tablist" aria-label="Explore ${s.name} deliverables">${s.items.map((item,i)=>`<button type="button" role="tab" id="scope-tab-${i}" aria-controls="scope-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-tab="${i}"><span>0${i+1}</span>${item}<b aria-hidden="true">↗</b></button>`).join('')}</div><div class="scope-display">${s.items.map((item,i)=>`<div role="tabpanel" id="scope-panel-${i}" aria-labelledby="scope-tab-${i}" ${i?'hidden':''}><span class="eyebrow">The detail / 0${i+1}</span><h3>${item}</h3><p>${detail[s.slug][i]}</p><a class="button" href="/contact?service=${s.slug}">Discuss this priority <span aria-hidden="true">↗</span></a></div>`).join('')}</div></div>`;
export function enrich(path,content){
 const s=services.find(x=>path==='/services/'+x.slug);
 if(path!=='/privacy'&&path!=='/404')content=content.replace('</h1>',`</h1><div class="inner-hero-art" data-tilt><img src="${path==='/about'?'/assets/asset-1.jpeg':'/assets/asset-2.jpeg'}" alt="CreatorFox’s nature and technology visual identity" width="1200" height="800"><span class="image-caption">Human instinct. Intelligent execution.</span></div>`);
 if(s){const add=section('Explore the scope','What the work looks like.',`<p class="intro">Select a priority to see what we do, why it matters and how it fits your business.</p>${matrix(s)}`)+section('Built for your business','A good fit starts with clarity.',`<div class="fit-grid"><article><span>01 / YOUR STARTING POINT</span><h3>${s.fit}</h3><p>Bring the work you already have: your website, brand material, reports or process notes. We build on useful foundations.</p></article><article><span>02 / WHAT YOU OWN</span><h3>Agreed deliverables.<br>Clear responsibilities.</h3><p>You receive the assets and documentation listed in your final scope. Access, usage rights and third-party costs are discussed before work begins.</p></article><article><span>03 / HOW WE REVIEW</span><h3>Meaningful checkpoints.<br>No mystery process.</h3><p>We agree on review dates and who signs off decisions. Progress is discussed in terms of your goals and the work delivered.</p></article></div>`)+section('Plan your next move','Start focused. Expand with purpose.',`<div class="engagement" data-engagement><div class="choice-row"><button type="button" aria-pressed="true" data-mode="focused">Focused project</button><button type="button" aria-pressed="false" data-mode="ongoing">Ongoing partnership</button></div><div data-mode-panel="focused"><h3>One clear challenge. An agreed scope.</h3><p>Ideal when you need ${s.name.toLowerCase()} around a launch, a specific problem or a defined deliverable. We agree the work, review points and handover before starting.</p><span class="pill">Typical engagement: ${s.time}</span></div><div data-mode-panel="ongoing" hidden><h3>A programme that learns as you grow.</h3><p>Suitable when your team needs continuing support. We plan priorities together, review delivery regularly and adjust the next cycle based on what your business needs.</p><span class="pill">Scope and review cadence agreed together</span></div><a class="button" href="/contact?service=${s.slug}">Find the right starting point ↗</a></div>`);
 content=content.replace('<section class="section dark">',add+'<section class="section dark">');
 }
 if(path==='/services')content=content.replace('<div class="service-grid">',`<div class="goal-finder"><label for="goal-choice">What would make the biggest difference?</label><select id="goal-choice"><option value="all">Explore all services</option><option value="brand">A stronger brand and website</option><option value="growth">More relevant attention and enquiries</option><option value="ai">A team that works smarter with AI</option></select><p id="goal-advice" role="status">Choose a goal to narrow down your starting points.</p></div><div class="service-grid">`);
 if(path==='/industries')content=content.replace('<div class="wrap cards">',`<div class="wrap"><div class="industry-filters" role="group" aria-label="Choose an industry"><button data-filter="all" aria-pressed="true">All industries</button><button data-filter="Retail">Retail</button><button data-filter="real estate">Property</button><button data-filter="Healthcare">Healthcare</button><button data-filter="Hospitality">Hospitality</button><button data-filter="B2B">B2B</button><button data-filter="Education">Education</button></div><div class="cards industry-cards">`).replace('</div></section>','</div></div></section>');
 if(path==='/about')content+=section('The way we work','Curiosity, with accountability.',`<div class="fit-grid"><article><span>01 / CLEAR THINKING</span><h3>Understand before prescribing.</h3><p>We ask about the business model, the customer and the constraint. The right recommendation starts with the right question.</p></article><article><span>02 / CONSIDERED CRAFT</span><h3>Make the details useful.</h3><p>Language, layout, motion and technology should help a person understand, decide or act. That is the standard we design around.</p></article><article><span>03 / SHARED OWNERSHIP</span><h3>Make progress visible.</h3><p>You should know what is being built, why it matters, what is ready for review and what comes next.</p></article></div>`);
 if(path==='/case-studies')content=content.replace('Explore how we approach common business challenges.', 'Explore how we approach common business challenges. Open a scenario to follow the problem, proposed response and measures of progress.');
 if(path.startsWith('/case-studies/'))content=content.replace('<div class="wrap prose">','<div class="wrap prose"><nav class="story-navigation" aria-label="Case study sections"><a href="#challenge">The challenge</a><a href="#approach">The approach</a><a href="#measurement">How we measure</a></nav>').replace('<span class="eyebrow">The challenge','<span id="challenge" class="eyebrow">The challenge').replace('<h2>The approach','<h2 id="approach">The approach').replace('<h2>How progress','<h2 id="measurement">How progress');
 return content;
}
