import {workPage,careersPage,originStory} from './editorial.mjs';
import {contactSection,industriesPage,workshopPage} from './redesign.mjs';
import references from '../data/references.json' with {type:'json'};
import services from '../data/services.json' with {type:'json'};
const detail={
'brand-kit': ['We examine who you serve, what customers value and how your competitors present themselves. You leave with an agreed positioning direction and a useful creative brief.','We develop a coherent identity system: logo variations, colour pairings, typography and clear rules for using them across digital and print.','Your brand guide explains the everyday decisions: how to introduce your business, write a headline, choose imagery and keep communication recognisable.','Launch with editable social and sales templates. Your team can produce consistent material without rebuilding the brand for every new post or pitch.'],
'3d-website-development':['We map the customer journey and identify the pages, product explanations and calls to action needed to turn interest into a meaningful next step.','Design and development work together. Layouts adapt to phones, tablets and desktops, with clear typography, accessible controls and reusable page components.','Interactive product views, depth and motion are added where they help people understand your offer. Mobile fallbacks preserve the story on less powerful devices.','We review metadata, indexability, forms, keyboard access and performance before launch. Handover includes practical guidance for maintaining the site.'],
'content-marketing':['We turn customer questions, buying objections and your expertise into a focused set of topics. Every topic has an audience, a purpose and a place in the journey.','Choose the formats that fit the message: articles that answer questions, short videos that demonstrate value and social posts that start a useful conversation.','AI assists with exploration and production. A human editor checks accuracy, tone, clarity and relevance, with your approval before publication.','A shared calendar makes the programme visible. Reviews connect content activity to meaningful engagement, enquiries and the questions your sales team hears.'],
'performance-marketing':['We choose channels around how your customers discover and buy, then agree the offer, budget, geography and quality criteria for an enquiry.','We review measurement before scaling spend. Conversion events, landing pages and lead handling need to tell a consistent story about campaign performance.','Campaigns become a disciplined sequence of tests: different creative, offers, audiences and landing-page messages, with decisions grounded in the available data.','Reporting explains what was spent, what happened and what changes next. Lead quality and business outcomes matter alongside clicks and impressions.'],
'influencer-marketing':['We shortlist creators around category, location, audience relevance and content quality. A large following alone is not a reason to select someone.','Available audience insights and engagement patterns inform due diligence. We document limitations rather than present follower-authenticity estimates as certainty.','A clear brief sets expectations for the story, format, dates, approvals and disclosure. Coordination keeps both the brand and creator aligned.','Usage rights and distribution are agreed before content goes live. The campaign review separates reach, engagement, traffic and attributable enquiries.'],
'aeo-geo':['We establish a baseline using agreed search terms and customer questions. This makes later visibility reviews more useful than isolated screenshots.','We organise expertise into clear topic areas and publish direct, evidence-led answers. Content is written for people making a decision, not just ranking systems.','Technical checks help search systems access and interpret your pages. Structured data is used only where it accurately represents the content.','We monitor a consistent set of queries, look for citation opportunities and refresh weak content. AI answer placement is variable and never guaranteed.'],
'ai-workshop':['Before the session, we identify the tasks taking up your team’s time, their confidence with AI and any restrictions on tools or business information.','Exercises use realistic business scenarios. Participants practise prompting, reviewing outputs and spotting where a human decision is still required.','The team leaves with reusable prompts, examples and workflow notes. The aim is something they can repeat confidently after the workshop ends.','We discuss safe information handling, verification and ownership. A short action plan identifies a few workflows to trial and how to review their value.'],
'digital-ai-consulting':['We map the journey from customer interest to delivery and identify where manual work, duplicated tools or unclear responsibilities create friction.','Each opportunity is assessed for usefulness, effort and risk. We consider whether a process should be simplified before adding another tool or automation.','The roadmap turns findings into an achievable sequence of work. Each priority has a purpose, owner, dependencies and a way to assess progress.','You can implement with your team or scope delivery with CreatorFox. Reviews focus on adoption and results, not simply whether a tool was installed.']};
detail['automation-ai-agents']=['Map each trigger, input and owner before connecting your CRM, email and business tools.','Build an assistant around approved business information, with clear limits and a route to a person.','Capture a structured brief, route the lead and prepare an outline for human review.','Test failure cases, record activity and train the team to maintain the workflow.'];
const section=(k,h,c)=>`<section class="section"><div class="wrap"><span class="eyebrow">${k}</span><h2>${h}</h2>${c}</div></section>`;
const visuals={
 'brand-kit':'/assets/home/843e9fb16a10bdfa.jpeg',
 '3d-website-development':'/assets/home/4f265906c4607fa9.png',
 'content-marketing':'/assets/home/5d607b7d14079d74.jpeg',
 'performance-marketing':'/assets/home/36eb5e528d87b8d4.jpeg',
 'influencer-marketing':'/assets/home/151e6cd6f47e2985.jpeg',
 'aeo-geo':'/assets/home/e3c3108ccc17cfb7.jpeg',
 'ai-workshop':'/assets/home/4f265906c4607fa9.png',
 'digital-ai-consulting':'/assets/home/4125fb93bc7cb689.jpeg'
};
visuals['automation-ai-agents']='/assets/home/4125fb93bc7cb689.jpeg';
const serviceContext={
 'brand-kit':'A clear identity makes every later decision faster: what to say, how to show it and what to repeat.',
 '3d-website-development':'The strongest interactive websites use motion to explain, guide and reward curiosity—not to distract from the next action.',
 'content-marketing':'A useful content system gives your team a repeatable way to build trust before a sales conversation.',
 'performance-marketing':'Paid media works best when the offer, landing page, tracking and follow-up process tell the same story.',
 'influencer-marketing':'Creator partnerships are stronger when relevance, creative fit, disclosure and usage rights are agreed before a post is made.',
 'aeo-geo':'AI search visibility begins with expertise that is easy for people and machines to understand, verify and reference.',
 'ai-workshop':'The aim is confidence: people learn where AI helps, where it needs review and how to turn one good experiment into a repeatable workflow.',
 'digital-ai-consulting':'A considered roadmap protects your team from buying another tool before understanding the process it should improve.'
};
serviceContext['automation-ai-agents']='Start with one bottleneck. Build a workflow your team can trust and maintain.';
const automationExamples=()=>`<div class="automation-grid"><article class="automation-card"><span class="automation-icon">01</span><h3>Enquiry triage</h3><p>Route a new enquiry by service, location and urgency so the right person sees the useful context first.</p></article><article class="automation-card"><span class="automation-icon">02</span><h3>Proposal preparation</h3><p>Turn a structured brief into a reviewable first outline, with a human responsible for scope and pricing.</p></article><article class="automation-card"><span class="automation-icon">03</span><h3>Content repurposing</h3><p>Transform one approved insight into a short article, social cut-downs and a sales-team answer without losing the original point.</p></article><article class="automation-card"><span class="automation-icon">04</span><h3>Internal knowledge search</h3><p>Help teams find the latest process, product or policy answer while keeping ownership and review visible.</p></article></div>`;
const contentPackage=()=>`<section class="section package-section"><div class="wrap"><span class="eyebrow">One visibility system</span><h2>AI content marketing + video, in one package.</h2><p class="intro">A practical monthly package for teams that want consistent ideas, polished production and a clear publishing rhythm—without handing the brand over to an unreviewed content machine.</p><div class="package-grid"><article class="package-card"><span class="eyebrow">01 / PLAN</span><h3>Message and calendar</h3><p>Audience themes, campaign angles, a monthly content calendar and channel-specific briefs tied to your offers.</p></article><article class="package-card"><span class="eyebrow">02 / CREATE</span><h3>AI-assisted content</h3><p>Human-edited articles, social posts, carousels, captions and short-form video scripts built from approved expertise.</p></article><article class="package-card"><span class="eyebrow">03 / SHOOT</span><h3>Video day + edits</h3><p>A focused half-day or full-day shoot, direction, b-roll plan, vertical cut-downs, captions and thumbnail-ready exports.</p></article><article class="package-card"><span class="eyebrow">04 / DISTRIBUTE</span><h3>Publish with care</h3><p>Scheduling support, creator or channel coordination, comment prompts and a review process for every important claim.</p></article><article class="package-card"><span class="eyebrow">05 / LEARN</span><h3>Useful reporting</h3><p>A simple monthly readout of reach, retention, saves, enquiries and the next content decisions—not vanity numbers alone.</p></article><article class="package-card"><span class="eyebrow">06 / FLEX</span><h3>Built around your team</h3><p>Use the package as a launch sprint, an ongoing content engine or a training handover. Final quantities are agreed after discovery.</p></article></div></div></section>`;
const serviceExamples={"brand-kit": [["A retail brand with one clear story", "Unify a store, caf\u00e9 and events under one identity: positioning, logo system, packaging and social templates."], ["A specialist made understandable", "Translate a complex B2B offer into a concise message, sales deck and consistent visual language."]], "content-marketing": [["One shoot. A month of stories.", "Plan a founder interview and product demonstration, then edit the footage into reels, customer answers and campaign assets."], ["AI video for a product launch", "Develop an approved concept, generate supporting scenes, add real product footage and finish with human-led editing and clear calls to action."]], "performance-marketing": [["Better-fit property enquiries", "Align location targeting, budget questions and landing-page messaging. Review qualified consultations alongside cost per lead."], ["A retail launch campaign", "Test product-led creative and distinct offers, then connect campaign reporting to store visits and attributable orders."]], "influencer-marketing": [["A local caf\u00e9 discovery campaign", "Match neighbourhood creators to the audience, coordinate visits and agree reels, stories, disclosure and usage rights."], ["A product demonstration series", "Brief category specialists to explain real use cases, then measure watch time, tracked visits and campaign enquiries."]], "aeo-geo": [["Expert answers for a B2B service", "Build answer pages around buyer questions, link to evidence and add accurate structured data. Monitor a consistent query set."], ["Local service discovery", "Clarify service locations, business details and FAQs so customers and search systems understand where the business can help."]], "ai-workshop": [["Marketing team practice lab", "Use one approved campaign brief to practise research, scripts and output review. Leave with a shared prompt library."], ["Operations workflow session", "Map a repetitive task, prototype a reviewed AI-assisted process and assign owners for a 30-day pilot."]], "digital-ai-consulting": [["From enquiry to proposal", "Route a structured lead to the right service, prepare a first outline and keep human approval before final pricing."], ["A searchable team playbook", "Organise approved process notes and help staff retrieve current answers with visible sources and content owners."]]};
const relatedWork=s=>section('Reference library','Explore the work. See the possibilities.',`<p class="intro">Selected public projects and educational resources, credited to their original creators. Third-party work is shown for reference, not as CreatorFox client work.</p><div class="reference-gallery">${references[s.slug].map(([title,credit,url,video,description,lesson])=>`<article class="reference-project">${video?`<div class="reference-media"><iframe src="https://www.youtube-nocookie.com/embed/${video}" title="${title} — ${credit}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe></div>`:`<a class="reference-cover" href="${url}" target="_blank" rel="noopener noreferrer">${title}<span aria-hidden="true">↗</span></a>`}<div class="reference-copy"><span class="reference-credit">${credit} · ${video?'Video reference':'External reference'}</span><h3>${title}</h3><p>${description}</p><details><summary>What to look for</summary><p>${lesson}</p></details><a href="${url}" target="_blank" rel="noopener noreferrer">${video?'Watch on YouTube':'Visit original work'} ↗</a></div></article>`).join('')}</div>`);
const matrix=(s)=>`<div class="scope-explorer" id="scope" data-explorer><div class="scope-tabs" role="tablist" aria-label="Explore ${s.name} deliverables">${s.items.map((item,i)=>`<button type="button" role="tab" id="scope-tab-${i}" aria-controls="scope-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-tab="${i}"><span>0${i+1}</span>${item}<b aria-hidden="true">↗</b></button>`).join('')}</div><div class="scope-display">${s.items.map((item,i)=>`<div role="tabpanel" id="scope-panel-${i}" aria-labelledby="scope-tab-${i}" ${i?'hidden':''}><span class="eyebrow">The detail / 0${i+1}</span><h3>${item}</h3><p>${detail[s.slug][i]}</p><a class="button" href="/contact?service=${s.slug}">Discuss this priority <span aria-hidden="true">↗</span></a></div>`).join('')}</div></div>`;

const serviceForm=s=>contactSection(s);
export function enrich(path,content){
 if(path==='/case-studies')return workPage();
 if(path==='/careers')return careersPage();
 if(path==='/about')content=content.replace(/<section class="section">[\s\S]*?<\/section>/,'')+originStory();
 if(path==='/industries')return industriesPage();
 if(path==='/services/ai-workshop')return workshopPage();
 const s=services.find(x=>path==='/services/'+x.slug); const heroImage=s?visuals[s.slug]:(path==='/about'?'/assets/about-founder-fox.jpg':'/assets/asset-2.jpeg');
 if(path!=='/privacy'&&path!=='/404'&&path!=='/about')content=content.replace('</h1>',`</h1><div class="inner-hero-art" data-tilt><img src="${heroImage}" alt="${s?`${s.name} work at CreatorFox`:'CreatorFox’s nature and technology visual identity'}" width="1200" height="800"><span class="image-caption">Human instinct. Intelligent execution.</span></div>`);
 if(s){const add=section('Explore the scope','What the work looks like.',`<p class="intro">Select a priority to see what we do, why it matters and how it fits your business.</p>${matrix(s)}`)+section('Built for your business','A good fit starts with clarity.',`<div class="fit-grid"><article><span>01 / YOUR STARTING POINT</span><h3>${s.fit}</h3><p>Bring the work you already have: your website, brand material, reports or process notes. We build on useful foundations.</p></article><article><span>02 / WHAT YOU OWN</span><h3>Agreed deliverables.<br>Clear responsibilities.</h3><p>You receive the assets and documentation listed in your final scope. Access, usage rights and third-party costs are discussed before work begins.</p></article><article><span>03 / HOW WE REVIEW</span><h3>Meaningful checkpoints.<br>No mystery process.</h3><p>We agree on review dates and who signs off decisions. Progress is discussed in terms of your goals and the work delivered.</p></article></div>`)+section('Plan your next move','Start focused. Expand with purpose.',`<div class="engagement" data-engagement><div class="choice-row"><button type="button" aria-pressed="true" data-mode="focused">Focused project</button><button type="button" aria-pressed="false" data-mode="ongoing">Ongoing partnership</button></div><div data-mode-panel="focused"><h3>One clear challenge. An agreed scope.</h3><p>Ideal when you need ${s.name.toLowerCase()} around a launch, a specific problem or a defined deliverable. We agree the work, review points and handover before starting.</p><span class="pill">Typical engagement: ${s.time}</span></div><div data-mode-panel="ongoing" hidden><h3>A programme that learns as you grow.</h3><p>Suitable when your team needs continuing support. We plan priorities together, review delivery regularly and adjust the next cycle based on what your business needs.</p><span class="pill">Scope and review cadence agreed together</span></div><a class="button" href="/contact?service=${s.slug}">Find the right starting point ↗</a></div>`);
 const context=section('A practical point of view',serviceContext[s.slug],`<div class="service-context-grid"><div><img src="${visuals[s.slug]}" alt="${s.name} work at CreatorFox" loading="lazy" width="900" height="650"></div><div><p>We connect the specialist work to the wider customer journey: discovery, confidence, decision and follow-through.</p><p>That means fewer disconnected deliverables and a clearer idea of what the work is meant to change.</p><a class="pill" href="/contact?service=${s.slug}">Talk through your situation ↗</a></div></div>`);
 const automation=['digital-ai-consulting','automation-ai-agents'].includes(s.slug)?section('Automation examples','Where practical AI can help.',`<p class="intro">These are starting points for a workshop or roadmap. We assess your process, data and team before recommending implementation.</p>${automationExamples()}`):'';
 const workshop=s.slug==='ai-workshop'?`<section class="workshop-landing" aria-labelledby="workshop-landing-title"><div class="workshop-landing-copy"><span class="eyebrow">For founders, marketing & operations teams</span><h2 id="workshop-landing-title">Turn AI curiosity into a useful working habit.</h2><p>Bring one repetitive task, one real business problem and the people responsible for the work. Leave with prompts, workflow notes and a practical 30-day action plan.</p><div class="workshop-proof"><span>Half-day or full-day</span><span>Live exercises</span><span>Take-home playbook</span></div><a class="button" href="#enquiry">Book an AI workshop <span aria-hidden="true">↗</span></a></div><div class="workshop-landing-art"><img src="/assets/workshop.webp" alt="Interactive AI workshop visual" loading="lazy" width="1000" height="820"></div></section><section class="section workshop-ad-section"><div class="wrap"><span class="eyebrow">What participants practise</span><div class="workshop-outcomes"><article><b>01</b><h3>Prompt with intent</h3><p>Give AI the context, constraints and examples needed for a useful first draft.</p></article><article><b>02</b><h3>Review with judgment</h3><p>Spot unsupported claims, missing nuance and the places where a human must decide.</p></article><article><b>03</b><h3>Build a repeatable flow</h3><p>Turn a successful experiment into a documented workflow your team can use next week.</p></article></div></div></section><section class="workshop-lead-capture"><div><span class="eyebrow">Bring your real question</span><h2>Plan a workshop your team will actually use.</h2><p>Share the workflow, audience and timing you have in mind. We’ll reply with a practical session outline and the right next step.</p></div><form id="enquiry" data-proposal-form><input name="name" minlength="2" maxlength="100" required aria-label="Your name" placeholder="Your name"><input type="email" name="email" required aria-label="Work email" placeholder="Work email"><input name="company" required maxlength="120" aria-label="Company" placeholder="Company"><input type="hidden" name="budget" value="To be discussed"><input type="hidden" name="timeline" value="To be discussed"><select name="service" aria-label="Service"><option value="ai-workshop">AI workshop</option></select><textarea name="goal" minlength="20" maxlength="2000" required aria-label="Workshop goals" placeholder="What should the team leave able to do?"></textarea><label class="cf-consent"><input type="checkbox" name="consent" required> I agree to be contacted about this enquiry.</label><input class="cf-hp" name="_gotcha" tabindex="-1" autocomplete="off" aria-hidden="true"><button class="button" type="submit">Request workshop outline <span aria-hidden="true">↗</span></button><p id="form-status" class="cf-form-status" role="status" aria-live="polite"></p></form></section>`:'';
 const packageSection=s.slug==='content-marketing'?contentPackage():'';
 content=workshop+packageSection+context+automation+relatedWork(s)+add+content+(s.slug==='ai-workshop'?'':serviceForm(s));
 }
 if(path==='/services')content=content.replace('<div class="service-grid">',`<div class="goal-finder"><label for="goal-choice">What would make the biggest difference?</label><select id="goal-choice"><option value="all">Explore all services</option><option value="brand">A stronger brand and website</option><option value="growth">More relevant attention and enquiries</option><option value="ai">A team that works smarter with AI</option></select><p id="goal-advice" role="status">Choose a goal to narrow down your starting points.</p></div><div class="service-grid">`);
 if(path==='/industries')content=content.replace('<div class="wrap cards">',`<div class="wrap"><div class="industry-filters" role="group" aria-label="Choose an industry"><button data-filter="all" aria-pressed="true">All industries</button><button data-filter="Retail">Retail</button><button data-filter="real estate">Property</button><button data-filter="Healthcare">Healthcare</button><button data-filter="Hospitality">Hospitality</button><button data-filter="B2B">B2B</button><button data-filter="Education">Education</button></div><div class="cards industry-cards">`).replace('</div></section>','</div></div></section>');
 if(path==='/about')content+=section('The way we work','Curiosity, with accountability.',`<div class="fit-grid"><article><span>01 / CLEAR THINKING</span><h3>Understand before prescribing.</h3><p>We ask about the business model, the customer and the constraint. The right recommendation starts with the right question.</p></article><article><span>02 / CONSIDERED CRAFT</span><h3>Make the details useful.</h3><p>Language, layout, motion and technology should help a person understand, decide or act. That is the standard we design around.</p></article><article><span>03 / SHARED OWNERSHIP</span><h3>Make progress visible.</h3><p>You should know what is being built, why it matters, what is ready for review and what comes next.</p></article></div>`)+section('People behind the work','A small senior team, extended when the work needs it.',`<div class="profile-grid"><article class="profile-card profile-lead"><span class="eyebrow">Founder / Digital marketing consultant</span><h3>Naveen Kumar</h3><p>Naveen leads CreatorFox with a focus on digital growth, creative strategy and practical AI adoption for business owners. His work connects positioning, customer acquisition and the systems that help teams deliver consistently.</p><a class="pill" href="https://www.linkedin.com/in/naveen-kumar-marketing/" target="_blank" rel="noopener noreferrer">View Naveen’s LinkedIn ↗</a></article><article class="profile-card"><span class="eyebrow">Strategy partner</span><h3>Pooja Das</h3><p>Brand strategy and customer research. Pooja helps teams turn a complex offer into a clear point of view and a confident first conversation.</p></article><article class="profile-card"><span class="eyebrow">Experience designer</span><h3>Thomas</h3><p>UX, interaction and content systems. Thomas shapes digital experiences that feel distinctive while staying easy to use on a phone.</p></article><article class="profile-card"><span class="eyebrow">AI workflow advisor</span><h3>Meera Iyer</h3><p>Operations, enablement and responsible AI use. Meera helps teams move from scattered experiments to documented, reviewable workflows.</p></article></div>`);
 if(path==='/case-studies')content=content.replace('Explore how we approach common business challenges.', 'Explore how we approach common business challenges. Open a scenario to follow the problem, proposed response and measures of progress.');
 if(path.startsWith('/case-studies/'))content=content.replace('<div class="wrap prose">','<div class="wrap prose"><nav class="story-navigation" aria-label="Case study sections"><a href="#challenge">The challenge</a><a href="#approach">The approach</a><a href="#measurement">How we measure</a></nav>').replace('<span class="eyebrow">The challenge','<span id="challenge" class="eyebrow">The challenge').replace('<h2>The approach','<h2 id="approach">The approach').replace('<h2>How progress','<h2 id="measurement">How progress');
 return content;
}
