import {PDFDocument, StandardFonts, rgb} from 'pdf-lib';
import services from '../data/services.json' with {type:'json'};
export async function makeProposal(input){
 const service=services.find(s=>s.slug===input.service);if(!service)throw new Error('Invalid service');
 const doc=await PDFDocument.create();const regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);let page,y;
 const plain=s=>String(s).normalize('NFKD').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/[–—]/g,'-').replace(/[^\x20-\x7E\n]/g,'');
 const fresh=()=>{page=doc.addPage([595,842]);y=760;page.drawRectangle({x:0,y:805,width:595,height:37,color:rgb(.07,.08,.06)});page.drawText('CREATORFOX / STARTING PROPOSAL',{x:45,y:819,size:10,font:bold,color:rgb(.91,.68,.33)});};fresh();
 function text(s,size=11,heading=false){const font=heading?bold:regular;let lines=[];for(const para of plain(s).split('\n')){let line='';for(let word of para.split(' ')){while(font.widthOfTextAtSize(word,size)>500){const cut=Math.max(1,Math.floor(word.length*490/font.widthOfTextAtSize(word,size)));lines.push(word.slice(0,cut));word=word.slice(cut)}const next=line?line+' '+word:word;if(font.widthOfTextAtSize(next,size)>500){lines.push(line);line=word}else line=next}lines.push(line)}for(const line of lines){if(y<65)fresh();page.drawText(line,{x:45,y,size,font,color:rgb(.10,.11,.09)});y-=size*1.55}y-=10}
 text(service.name,27,true);text('Prepared for '+input.name+' / '+input.company,12);text('Initial service outline - subject to discovery and agreement.',10);text('Your goal',15,true);text(input.goal);text('Recommended starting point',15,true);text(service.intro);text('Proposed deliverables',15,true);service.items.forEach((s,i)=>text(`${i+1}. ${s}`));text('Typical engagement',15,true);text(service.time+'. Dates depend on final scope, approvals and resource availability.');text('Budget and commercial terms',15,true);text('Budget preference: '+input.budget+'. This is not a binding quote. Fees, payment terms, third-party costs and final scope will be confirmed in a separate priced proposal.');text('Next steps',15,true);text('CreatorFox will review your brief and follow up to clarify priorities. Reply to the proposal email with any useful links or questions.');text('Contact: make.creatorfox@gmail.com',11,true);
 for(const [i,p] of doc.getPages().entries())p.drawText(`CreatorFox | ${i+1} / ${doc.getPageCount()} | Confidential enquiry outline`,{x:45,y:30,size:9,font:regular,color:rgb(.4,.4,.4)});
 return Buffer.from(await doc.save());
}
