import type {Metadata} from "next";
import Link from "next/link";
import {ArrowLeft,ArrowUpRight,CheckCircle2} from "lucide-react";
import {Footer,Navbar,Reveal} from "../../../components/SiteUI";
import EvilEye from "../../../components/EvilEye";
import site from "../../../content/site.json";
const seo:Record<string,{title:string;description:string;keywords:string[];image:string}>= {
 "brand-identity":{title:"Brand Identity Design Agency India",description:"Premium brand identity, positioning, visual identity and brand strategy for ambitious companies in India.",keywords:["brand identity design India","branding agency India","brand strategy","visual identity design"],image:"https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1800&q=90"},
 "website-development":{title:"Website Development Agency India | Premium Websites",description:"SEO-friendly, high-performance website development focused on UX, conversion, speed, accessibility and growth.",keywords:["website development agency India","premium website design","SEO website development","conversion focused website"],image:"https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1800&q=90"},
 "content-strategy":{title:"Content Marketing Strategy Agency India",description:"Build a repeatable content marketing engine with strategy, creative direction, distribution and performance measurement.",keywords:["content marketing agency India","content strategy","social media content strategy","content marketing"],image:"https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1800&q=90"},
 "performance-marketing":{title:"Performance Marketing Agency India | Google & Meta Ads",description:"Performance marketing and paid advertising across Google, Meta and LinkedIn built around qualified leads, sales and ROAS.",keywords:["performance marketing agency India","Google Ads agency","Meta Ads agency","PPC agency India","ROAS optimization"],image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1800&q=90"},
 "creator-marketing":{title:"Influencer Marketing Agency India | Creator Campaigns",description:"Indian influencer and creator marketing campaigns with discovery, shortlisting, negotiation, campaign execution and reporting.",keywords:["influencer marketing agency India","creator marketing India","Instagram influencer campaigns","creator marketplace India"],image:"https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1800&q=90"},
 "ai-automation":{title:"AI Automation Agency India | AI Agents & Workflows",description:"AI automation, custom AI agents and intelligent workflows for marketing, sales, support, reporting and operations.",keywords:["AI automation agency India","AI agents","business automation","marketing automation","AI workflow automation"],image:"https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1800&q=90"},
 "ai-workshops":{title:"Executive AI Workshops India | AI Training",description:"Hands-on executive AI workshops for founders, leaders and marketing teams focused on practical business adoption.",keywords:["AI workshop India","executive AI training","AI training for businesses","AI workshop for marketing teams"],image:"https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1800&q=90"}
};
export function generateStaticParams(){return site.services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:{slug:string}}):Promise<Metadata>{const s=seo[params.slug]||seo["brand-identity"];return{title:s.title,description:s.description,keywords:s.keywords,openGraph:{title:s.title,description:s.description,images:[s.image]}}}
export default function ServicePage({params}:{params:{slug:string}}){const service=site.services.find(s=>s.slug===params.slug)||site.services[0];const s=seo[params.slug]||seo["brand-identity"];return <main><Navbar/><section className="relative min-h-[78vh] overflow-hidden bg-[#080808] pt-40 text-white sm:pt-48"><img src={s.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-20"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_40%,rgba(187,124,29,.2),transparent_32%),linear-gradient(90deg,#080808,rgba(8,8,8,.75),#080808)]"/><div className="absolute right-[8%] top-[24%] h-64 w-64 opacity-80"><EvilEye/></div><div className="relative mx-auto max-w-[1500px] px-5 sm:px-8"><Reveal><Link href="/services" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-white/45 hover:text-white"><ArrowLeft size={14}/> All services</Link><p className="eyebrow mt-14 text-[#BB7C1D]">{service.title}</p><h1 className="display mt-5 max-w-5xl">{service.title}<span className="text-[#BB7C1D]">.</span></h1><p className="mt-8 max-w-2xl text-base leading-7 text-white/50">{service.short}</p></Reveal></div></section><section className="bg-[#f7f7f5] py-24 sm:py-32"><div className="mx-auto grid max-w-[1500px] gap-14 px-5 sm:px-8 lg:grid-cols-[.75fr_1.25fr]"><Reveal><p className="eyebrow text-[#BB7C1D]">How we approach it</p><h2 className="mt-6 text-4xl font-bold leading-tight tracking-[-.05em] sm:text-6xl">Designed around<br/>the <span className="text-[#BB7C1D]">outcome.</span></h2></Reveal><Reveal delay={.08}><p className="text-lg leading-8 text-black/60">{service.short} We build the strategy, creative system, execution plan and measurement layer around the business problem — then keep improving it.</p><div className="mt-12 grid gap-3 sm:grid-cols-2">{['Strategy & discovery','Creative direction','Execution system','Measurement & optimization'].map(x=><div key={x} className="flex items-center gap-3 rounded-2xl bg-white p-5"><CheckCircle2 className="text-[#BB7C1D]" size={19}/><span className="text-sm font-semibold">{x}</span></div>)}</div><Link href="/contact" className="mt-10 inline-flex items-center gap-3 rounded-full bg-[#2B2B2B] px-5 py-3 text-[11px] font-bold uppercase tracking-[.14em] text-white">Discuss this service <ArrowUpRight size={15}/></Link></Reveal></div></section><Footer/></main>}
